-- Final SQL Project - Shop
-- Daria Kusz
-- Emilia Mrosek


-- A few searches 

-- Using the orders_per_month view, check in which month there were the most orders
SELECT * FROM orders_per_month 
WHERE order_count = (SELECT MAX(order_count) FROM orders_per_month);

-- Using the orders_total view, check how much the customer spent in total for order 00010
SELECT * FROM orders_total WHERE order_number = '00010';

-- From the same view, we can check the total revenue generated by the company from online orders
SELECT SUM(total_spent) AS total_revenue FROM orders_total;

-- We can also check the customers who spent the most (TOP 3)
SELECT customer, SUM(total_spent) FROM orders_total
GROUP BY customer
ORDER BY SUM(total_spent) DESC
LIMIT 3;

-- Check if any product is sold out
SELECT * FROM products
WHERE stock_quantity = 0;

-- Check how many bikes were sold from each category
SELECT p.category, SUM (od.quantity) AS total_sold
FROM products p
INNER JOIN order_details od ON od.product_id = p.product_id
GROUP BY p.category
ORDER BY SUM (od.quantity) DESC; 

-- Average number of products in a single order
SELECT ROUND(AVG(quantity),0)::text || ' pieces' AS avg_products_per_order FROM order_details;

-- Check the average shipping time of an order
SELECT ROUND(AVG(ship_date - order_date),0)::text || ' days'  AS avg_shipping_time
FROM orders
WHERE ship_date IS NOT NULL;

-- And average delivery time of the bike to the customer
SELECT ROUND(AVG(delivery_date - order_date),0)::text || ' days'  AS avg_delivery_time
FROM orders
WHERE delivery_date IS NOT NULL;

-- Also average delivery realization time calculated from shipping date to delivery date
SELECT ROUND(AVG(delivery_date - ship_date),0)::text || ' days'  AS avg_transit_time
FROM orders
WHERE delivery_date IS NOT NULL;

-- Check orders that haven't been shipped yet using orders_view
SELECT order_number, order_date, order_status FROM orders_view WHERE order_status = 'processing';

-- List of orders with their current status
SELECT order_number, order_status
FROM orders_view;

-- Now we will check the function searching for an order by ID for the customer
\c bike_shop customer
-- After attempting to search orders from the orders view by the customer, an error should pop up. The customer should not have access to other clients' data
SELECT * FROM orders_view;

-- The customer (knowing the order ID) can search for information about their order. They can search for everything:
SELECT * FROM search_orders('00007');

-- As well as specific things that interest them, e.g., order status and the address it is being shipped to
SELECT address, status FROM search_orders('00011');
SELECT address, status FROM search_orders('00012');